### ISSUE TITLE
Improve hourly labelling at night

### ISSUE THREAD

**Issue by JanDetrez** [jdejaegh/irm-kmi-ha#16]
Hi

Great integration to have as a Belgian!

Would it be possible to improve the labelling during the night, so weather Lovelace integrations would show a moon instead of a sun in case it is 'partly cloudy' during the night?

I'm not sure if this is accessible through the KMI data you pull, although the KMI website does properly show a moon during 'partly cloudy' at night. If not available, perhaps  sunrise and sundown hours are available so one could write a workaround to have a 'partly cloudy night' condition.

I also asked if perhaps the Lovelace integration I use can add this particular label, or if it can make an override during the night.https://github.com/decompil3d/lovelace-hourly-weather/issues/662

As you see below, it is a bit odd that during the night we see this 'partly cloudy' condition with a sun.

Thanks for considering this improvement.

For example
![Screenshot_20240331-064528](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/8d856d3b-87f5-48af-8834-86160cb9b4f2)
![Screenshot_20240331-064129](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/778e4fea-30a5-4a6a-9ecb-54e2f968cbd7)
![Screenshot_20240331-064120](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/0514ae4b-10f6-4ee5-b570-7cb189c2cfb3)

**Comment by jdejaegh** [comment]
Thanks for your feedback on the integration!

I also noticed that the 'partly cloudy' condition shows the sun with clouds in most weather cards, even at night.  

For the integration, I am following the [Recommended values for state and condition](https://developers.home-assistant.io/docs/core/entity/weather/#recommended-values-for-state-and-condition) from the developer documentation.  As you may notice, most conditions are not tied to daytime or nighttime.

I am not really keen on adding new custom conditions, as they will not be supported by most Lovelace cards.  Having a partly cloudy icon with the sun (even at night) is IMHO better than a broken icon because of a custom weather condition value.

Regarding the KMI data I pull, yes it includes if the forecast is for day or night.  This is even returned by the [standard `is_daytime` attribute](https://developers.home-assistant.io/docs/core/entity/weather/#forecast-data) in the service call.  This can be used by Lovelace cards to adapt the icon they use.


<details>
  <summary>Example of service call response</summary>

```yaml
weather.bxl:
  forecast:
    - datetime: "2024-03-31T20:00:00"
      condition: cloudy
      precipitation_probability: 0
      wind_bearing: SSE
      is_daytime: true
      temperature: 14
      pressure: 992
      wind_speed: 10
      precipitation: 0
    - datetime: "2024-03-31T21:00:00"
      condition: pouring
      precipitation_probability: 50
      wind_bearing: S
      is_daytime: false
      temperature: 13
      pressure: 993
      wind_speed: 10
      precipitation: 0.1
```
  
</details>

The best is to have the card implementing their own logic as they have all the data they need (condition and daytime).  Some other weather card have that kind of logic.  For example

- [pkissling/clock-weather-card](https://github.com/pkissling/clock-weather-card/blob/7daf6a297c5dfb37f533709d1ed25628d96aeee3/src/clock-weather-card.ts#L432)
- [mlamberts78/weather-chart-card](https://github.com/mlamberts78/weather-chart-card/blob/930a68b86afd892348b4940b8353f92939c8f052/src/main.js#L275)

For compatibility reasons, I won't add a custom weather condition value.  Rather, Lovelace cards should have some logic to handle the issue raised here.  I hope you understand why and how it is done in other cards
