### ISSUE TITLE
Problem pasing daily forecast

### ISSUE THREAD

**Issue by Woutch** [jdejaegh/irm-kmi-ha#49]
**Describe the bug**
Daily forecast using the script bellow returns puts a long string in the entity, hourly is getting processed correctly

**Script**
```
#weather forcast daily sensor 
- trigger:
    - platform: time_pattern
      minutes: 55

    - platform: homeassistant
      event: start
  action:
    - service: weather.get_forecasts
      data:
        type: daily
      target:
        entity_id: weather.home
      response_variable: daily

  sensor:
    - name: Weather Daily
      state: "{{ states('weather.home') }}"
      attributes:
        temperature: "{{ state_attr('weather.home', 'temperature') }}"
        dew_point: "{{ state_attr('weather.home', 'dew_point') }}"
        temperature_unit: "{{ state_attr('weather.home', 'temperature_unit') }}"
        humidity: "{{ state_attr('weather.home', 'humidity') }}"
        cloud_coverage: "{{ state_attr('weather.home', 'cloud_coverage') }}"
        pressure: "{{ state_attr('weather.home', 'pressure') }}"
        pressure_unit: "{{ state_attr('weather.home', 'pressure_unit') }}"
        wind_bearing: "{{ state_attr('weather.home', 'wind_bearing') }}"
        wind_speed: "{{ state_attr('weather.home', 'wind_speed') }}"
        wind_speed_unit: "{{ state_attr('weather.home', 'wind_speed_unit') }}"
        visibility_unit: "{{ state_attr('weather.home', 'visibility_unit') }}"
        precipitation_unit: "{{ state_attr('weather.home', 'precipitation_unit') }}"
        forecast: "{{ daily['weather.home'].forecast }}"
```

I have practcally the same script for hourly. T problem lies with the last line:   forecast: "{{ daily['weather.home'].forecast }}"

Working hourly: {{ state_attr('sensor.weather_hourly','forecast') }}
Output is a array:
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/3136903/ddaf8a6f-de42-4e8d-bbe4-25e11f39c61f)

Not working Daily: {{ state_attr('sensor.weather_daily','forecast') }}
Ouptus is a string: 
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/3136903/bb7f0eb7-e44f-4d6c-9265-038bd90db56f)

So the following template "{{ state_attr('sensor.weather_daily','forecast')[3]}}" returns the 4th char: d, and not the 4th day.

So something is broken to parse the json into an array I guess? Maybe the single quotes in forecast text? like 's morgens?

**Version**
 - Home Assistant: 2024.6.3
 - IRM KMI integration 0.2.17

Love the integration by the way ;-)

Thanks Wouter
