### ISSUE TITLE
[HA 2025.1.4] Cannot install integration (Error Config flow could not be loaded: {"message":"Invalid handler specified"})

### ISSUE THREAD

**Issue by vanThijs** [jdejaegh/irm-kmi-ha#68]
**Describe the bug**
The application is prepared through HACS, but fails upon installation in Home Assistant. The integration is not added to Home Assistant.

**To Reproduce**
1. Install via integration via HACS
2. Reboot HA
3. Install the integation via "Devices & Services"
4. Error occurs immediately afterwards (Popup message: Error Config flow could not be loaded: {"message":"Invalid handler specified"})

**Expected behavior**
I expect the integration to install as intended :)

**Screenshots**
![Image](https://github.com/user-attachments/assets/cebd3425-78b6-470f-9dd7-dae52d56bc1c)

An error is logged in the general error logs:
![Image](https://github.com/user-attachments/assets/f996efa4-43cc-4b46-af96-f7ded2208258)

**Version**
 - Home Assistant: [Core: 2025.1.4, Frontend: 20250109.2], installed in a Container on a Synology NAS
 - IRM KMI integration [0.2.25]

**Comment by jdejaegh** [comment]
I followed those steps to reproduce the issue without success:

1. Install Home Assistant 2025.1.4 with Docker (see docker-compose file below)
2. Start the container
3. Install HACS
4. Restart the container
5. Setup the basic information on first use
6. Install the integration via the HACS UI
7. The integration works and is shown on the default dashboard

Here is the `docker-compose.yml` file.

```yml
services:
  homeassistant:
    container_name: homeassistant
    image: docker.io/homeassistant/home-assistant:2025.1.4
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8123:8123"
```

Could you provide the debug logs that are generated when you trigger the bug?

This seems related to #60 and https://github.com/home-assistant/core/issues/127966

Note that the error `No module named 'svgwrite'` is coming from Home Assistant itself.  It probably failed to installed svgwrite (a dependency of this integration) when loading the integration.  If this is the actual problem here, there is not much I can change in the integration to fix it: the bug should be reported to Home Assistant.
