### ISSUE TITLE
Numeric index attribute for pollen sensors

### ISSUE THREAD

**Issue by SVANNER** [jdejaegh/irm-kmi-ha#87]
**Is your feature request related to a problem? Please describe.**
No. I try to use a gauge card in HA to visualize the pollen sensor

**Describe the solution you'd like**
As the gauge does not accept other  index than a number, I would like to have a numeric attribute to pass to the gauge card.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jdejaegh** [comment]
Hello,

I get the idea of the gauge to show the pollen level (similar to the image below from the IRM KMI application, I guess)

<img height="200" src="https://github.com/jdejaegh/irm-kmi-ha/raw/main/img/pollens.png" alt="Pollen data"/>

As the integration currently provides string attribute, changing to a numeric value will break things for users relying on the current values.  However, I think that a template sensor could help you with mapping the colors to numeric values and use a gauge card.

I don't really have time now to check how to write such template but I can check that later and post it here.

**Comment by SVANNER** [comment]
Hello jdejaegh,

Thanks for your quick answer. I got the same idea in the mean time (I am just in the starting blocks of my learning curve for Home Assistant ;-)). I used a combination of templates and macro to render a numeric value for usin the [Canvas gauge card](https://github.com/custom-cards/canvas-gauge-card) having the following result:

![Image](https://github.com/user-attachments/assets/5a037c38-931f-4b07-b2dc-616c2fcfa38e)

Here is the code  I used to achieve the job, in case this can help somebody else:

```
{% macro get_pollen_severity_index(sensor_id, attribute) %}
{% set severity = [
    {'state': 'none', 'index': 0 | int, 'label': 'None'},
    {'state': 'active', 'index': 1 | int, 'label': 'Active'},
    {'state': 'green', 'index': 3 | int, 'label': 'None'},
    {'state': 'yellow', 'index': 5 | int, 'label': 'Low'},
    {'state': 'orange', 'index': 7 | int, 'label': 'Moderate'},
    {'state': 'red', 'index': 9 | int, 'label': 'High'},
    {'state': 'purple', 'index': 11 | int, 'label': 'Very high'}
    ] %}
{% set state_value = states(sensor_id) %}
{% set ns = namespace(state=0, label='None') %}
{% for item in severity %}
    {% if state_value == item.state %}
        {% set ns.state = item.index %}
        {% set ns.label = item.label %}
    {% endif %}
{% endfor %}
{% if attribute == 0 %}
    {{ ns.state }}
{% else %}
    {{ ns.label }}
{% endif %}
{% endmacro %}
```


Then, I created a template for each of the sensors. Here is an example:

```
     - name: severity_grasses
       unique_id: "72e38c17-9a66-491e-8e09-734ad8d4aa8f"
       state: >
         {% from 'pollen_severity.jinja' import get_pollen_severity_index %}
         {{ get_pollen_severity_index('sensor.irm_grasses_level', 0) | int }}
```

and finally the code for the gauge:

```
  - type: custom:canvas-gauge-card
    visibility:
      - condition: state
        entity: sensor.severity_grasses
        state_not: "0"
      - condition: state
        entity: sensor.severity_grasses
        state_not: "1"
    entity: sensor.severity_grasses
    card_height: 120
    gauge:
      type: radial-gauge
      title: Grasses
      shadow_height: 15%
      font_size: 1em
      width: 200
      height: 200
      borderShadowWidth: 0
      borderOuterWidth: 0
      borderMiddleWidth: 0
      borderInnerWidth: 0
      minValue: 1
      maxValue: 12
      startAngle: 90
      ticksAngle: 180
      valueBox: false
      majorTicks:
        - " "
        - None
        - " "
        - Low
        - " "
        - Moderate
        - " "
        - High
        - " "
        - Very high
        - " "
      minorTicks: null
      strokeTicks: true
      highlights:
        - from: 1
          to: 3.2
          color: green
        - from: 3.2
          to: 5.45
          color: yellow
        - from: 5.45
          to: 7.54
          color: orange
        - from: 7.54
          to: 9.8
          color: red
        - from: 9.8
          to: 12
          color: purple
      borders: false
```
