### ISSUE TITLE
Rain prediction without full map

### ISSUE THREAD

**Issue by JanDetrez** [jdejaegh/irm-kmi-ha#88]
Would it be possible to display only the prediction without the full map, like this?

![Image](https://github.com/user-attachments/assets/f6bfcea2-6163-46d4-ad53-7d4fd54f10f9)

**Comment by SVANNER** [comment]
Indeed. Moreover, it should be great to get the same info as sensor (in place of a service call) that reflects the next rain prevision in x minutes and having the mm/10 minutes as an attribute.

**Comment by bilalhp** [comment]
A datetime sensor indicating the "next rain" would be great. I will try to create a template sensor using the service call when I have some time, but a native sensor would be great. Unfortunately, I am not experienced enough to implement this in the python code.

**Comment by bilalhp** [comment]
@SVANNER this can be a good starting point for you:

``` 
  - trigger:
      - platform: time_pattern
        minutes: "/10"
      - trigger: homeassistant
        event: start
    action:
      - service: irm_kmi.get_forecasts_radar
        data: {}
        target:
          entity_id: weather.home
        response_variable: resp
    sensor:
      - name: "Weather Forecast RMI Radar"
        unique_id: weather_forecast_rmi_radar
        device_class: precipitation_intensity
        state_class: measurement
        unit_of_measurement: mm/h
        state: "{{ resp['weather.home'][0].native_precipitation }}"
        attributes:
          rain_forecast_max: "{{ resp['weather.home'][0].rain_forecast_max }}"
          rain_forecast_min: "{{ resp['weather.home'][0].rain_forecast_min }}"
          might_rain: "{{ resp['weather.home'][0].might_rain }}"
          next_rain: "{{ (resp['weather.home']|selectattr('native_precipitation', '>', 0.01)|first).datetime }}"
          next_rain_amount: "{{ (resp['weather.home']|selectattr('native_precipitation', '>', 0.01)|first).native_precipitation }}"
          forecast: "{{ resp['weather.home'] }}"
  - sensor:
      - name: "RMI forecast next rain"
        unique_id: "rmi_forecast_next_rain"
        device_class: timestamp
        state: "{{ state_attr('sensor.weather_forecast_rmi_radar', 'next_rain') }}"
        attributes:
            amount: "{{ state_attr('sensor.weather_forecast_rmi_radar', 'next_rain_amount') }}"
        availability: "{{ has_value('sensor.weather_forecast_rmi_radar') }}"
```
