### ISSUE TITLE
Warning type: heat

### ISSUE THREAD

**Issue by cmdduck** [jdejaegh/irm-kmi-ha#89]
As captured today, id: 10 means Heat, Chaleur, Hitze, Hitte
This type is not mentioned on the readme.

```
warnings:
  - slug: unknown
    id: 10
    level: 1
    friendly_name: Heat
    text: >-
      By such temperatures, measures should be taken to protect older and weaker
      persons by giving them more often to drink and to not let them stand or
      sit in direct sunlight. Be careful.
    starts_at: "2025-06-13T00:00:00+02:00"
    ends_at: "2025-06-14T00:00:00+02:00"
    is_active: true
active_warnings_friendly_names: Heat
attribution: Weather data from the Royal Meteorological Institute of Belgium meteo.be
```
